# Етап 1: Збірка
FROM maven:3.9.5-eclipse-temurin-17 AS build
WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline

COPY src ./src
RUN mvn clean package -DskipTests

# Етап 2: Запуск
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

# Відкриваємо порт 8081 (згідно з ТЗ)
EXPOSE 8081

ENTRYPOINT ["java", "-jar", "app.jar"]